### ISSUE TITLE
douyin创作者的cookies问题

### ISSUE THREAD

**Issue by kylexiaox** [aceliuchanghong/bili_douyin_xhs_uploader#2]
https://creator.douyin.com/creator-micro/content/upload 的cookie塞进去，json格式。playwright打开后页面依旧需要登录。

**Comment by aceliuchanghong** [comment]
playwright打开后页面依旧需要登录是cookie有误

对应cookie的获取我确实没有写.
这个我使用的时候是通过chrome登陆之后再用插件:Cookie Master获取的,但是还需要替换几个地方,可以根据具体报错自己替换
大概是:
"sameSite": "Lax",
