### ISSUE TITLE
可不可以补充获取cookie的方式

### ISSUE THREAD

**Issue by liren-sun** [aceliuchanghong/bili_douyin_xhs_uploader#4]

**Comment by aceliuchanghong** [comment]
我是通过chrome的插件:Cookie Master获取的
https://chromewebstore.google.com/detail/cookie-master/jahkihogapggenanjnlfdcbgmldngnfl

复制之后,还需要替换几个地方
大概是sameSite之类的:
"sameSite": "Lax",
可以根据具体报错自己替换
